-- ============================================================
-- Demo menu seed — safe to run anytime. Uses ON CONFLICT DO NOTHING
-- so it will never duplicate or overwrite anything already in your
-- database. Use this to make sure the site has a full, realistic-
-- looking menu before showing it to a client.
-- ============================================================

-- Categories
insert into categories (id, name_ar, name_en, image, description_ar, description_en, is_visible, "order") values ('cat-1', 'كباب ومشاوي', 'Kebabs & Grills', '/images/categories/kebabs.jpg', 'أصناف الكباب والمشاوي على الفحم', 'Charcoal grilled kebabs and grills', true, 1) on conflict (id) do nothing;
insert into categories (id, name_ar, name_en, image, description_ar, description_en, is_visible, "order") values ('cat-2', 'دجاج مشوي', 'Grilled Chicken', '/images/categories/chicken.jpg', 'دجاج مشوي على الفحم', 'Charcoal grilled chicken', true, 2) on conflict (id) do nothing;
insert into categories (id, name_ar, name_en, image, description_ar, description_en, is_visible, "order") values ('cat-3', 'لحوم', 'Meat', '/images/categories/meat.jpg', 'أصناف اللحوم المشوية', 'Grilled meat dishes', true, 3) on conflict (id) do nothing;
insert into categories (id, name_ar, name_en, image, description_ar, description_en, is_visible, "order") values ('cat-4', 'مأكولات بحرية', 'Seafood', '/images/categories/seafood.jpg', 'مأكولات بحرية مشوية', 'Grilled seafood', true, 4) on conflict (id) do nothing;
insert into categories (id, name_ar, name_en, image, description_ar, description_en, is_visible, "order") values ('cat-5', 'مقبلات', 'Appetizers', '/images/categories/appetizers.jpg', 'مقبلات وسلطات', 'Appetizers and salads', true, 5) on conflict (id) do nothing;
insert into categories (id, name_ar, name_en, image, description_ar, description_en, is_visible, "order") values ('cat-6', 'مشروبات', 'Drinks', '/images/categories/drinks.jpg', 'عصائر ومشروبات', 'Fresh juices and drinks', true, 6) on conflict (id) do nothing;

-- Menu items
insert into menu_items (id, name_ar, name_en, description_ar, description_en, price, image, category_id, preparation_time, calories, is_available, is_featured, is_popular, is_vegetarian, is_spicy, created_at, options) values ('mi-1', 'كفتة مشوية', 'Grilled Kofta', 'لحم مفروم متبل مشوي على الفحم مع خبز وطحينة', 'Spiced minced lamb grilled on charcoal with bread and tahini', 85, '/images/menu/kofta.jpg', 'cat-1', 15, 420, true, true, true, false, false, '2024-01-01', '[{"id":"opt-1","nameAr":"صوص إضافي","nameEn":"Extra Sauce","price":5},{"id":"opt-2","nameAr":"خبز إضافي","nameEn":"Extra Bread","price":3}]'::jsonb) on conflict (id) do nothing;
insert into menu_items (id, name_ar, name_en, description_ar, description_en, price, image, category_id, preparation_time, calories, is_available, is_featured, is_popular, is_vegetarian, is_spicy, created_at, options) values ('mi-2', 'مشكل مشاوي', 'Mixed Grill', 'تشكيلة من الكفتة والدجاج واللحوم مع أرز وخبز وصوص', 'Assortment of kofta, chicken, and meats with rice, bread, and sauces', 220, '/images/menu/mixed-grill.jpg', 'cat-1', 25, 850, true, true, true, false, false, '2024-01-01', '[{"id":"opt-3","nameAr":"أرز إضافي","nameEn":"Extra Rice","price":10},{"id":"opt-4","nameAr":"سلطة إضافية","nameEn":"Extra Salad","price":8}]'::jsonb) on conflict (id) do nothing;
insert into menu_items (id, name_ar, name_en, description_ar, description_en, price, image, category_id, preparation_time, calories, is_available, is_featured, is_popular, is_vegetarian, is_spicy, created_at, options) values ('mi-3', 'شيش طاووق', 'Shish Tawook', 'قطع دجاج متبلة على السيخ مع فلفل ألوان وبصل مشوي', 'Marinated chicken chunks on skewers with bell peppers and grilled onions', 95, '/images/menu/shish-tawook.jpg', 'cat-1', 18, 380, true, false, false, false, false, '2024-01-02', NULL) on conflict (id) do nothing;
insert into menu_items (id, name_ar, name_en, description_ar, description_en, price, image, category_id, preparation_time, calories, is_available, is_featured, is_popular, is_vegetarian, is_spicy, created_at, options) values ('mi-4', 'شاورما دجاج', 'Chicken Shawarma', 'دجاج شاورما متبل مع ثومية ومخلل وبطاطس', 'Spiced shawarma chicken with garlic sauce, pickles, and fries', 60, '/images/menu/shawarma.jpg', 'cat-2', 10, 520, true, false, true, false, false, '2024-01-01', NULL) on conflict (id) do nothing;
insert into menu_items (id, name_ar, name_en, description_ar, description_en, price, image, category_id, preparation_time, calories, is_available, is_featured, is_popular, is_vegetarian, is_spicy, created_at, options) values ('mi-5', 'دجاج مشوي كامل', 'Whole Grilled Chicken', 'دجاجة كاملة مشوية على الفحم مع ثومية وبطاطس', 'Whole chicken charcoal grilled with garlic sauce and fries', 180, '/images/menu/shish-tawook.jpg', 'cat-2', 30, 1200, true, true, false, false, false, '2024-01-03', NULL) on conflict (id) do nothing;
insert into menu_items (id, name_ar, name_en, description_ar, description_en, price, image, category_id, preparation_time, calories, is_available, is_featured, is_popular, is_vegetarian, is_spicy, created_at, options) values ('mi-6', 'ريش ضأن', 'Lamb Chops', 'ريش ضأن مشوية على الفحم متبلة بأعشاب خاصة', 'Charcoal grilled lamb chops seasoned with special herbs', 250, '/images/menu/lamb-chops.jpg', 'cat-3', 25, 680, true, true, true, false, false, '2024-01-01', NULL) on conflict (id) do nothing;
insert into menu_items (id, name_ar, name_en, description_ar, description_en, price, image, category_id, preparation_time, calories, is_available, is_featured, is_popular, is_vegetarian, is_spicy, created_at, options) values ('mi-7', 'ستيك لحم', 'Beef Steak', 'ستيك لحم بقري مشوي مع صوص الفلفل والمشروم', 'Grilled beef steak with pepper and mushroom sauce', 200, '/images/menu/lamb-chops.jpg', 'cat-3', 22, 650, true, false, false, false, false, '2024-01-04', NULL) on conflict (id) do nothing;
insert into menu_items (id, name_ar, name_en, description_ar, description_en, price, image, category_id, preparation_time, calories, is_available, is_featured, is_popular, is_vegetarian, is_spicy, created_at, options) values ('mi-8', 'جمبري مشوي', 'Grilled Shrimp', 'جمبري كبير مشوي على الفحم مع زبدة وثوم وليمون', 'Large shrimp charcoal grilled with butter, garlic, and lemon', 160, '/images/categories/seafood.jpg', 'cat-4', 20, 320, true, false, false, false, true, '2024-01-05', NULL) on conflict (id) do nothing;
insert into menu_items (id, name_ar, name_en, description_ar, description_en, price, image, category_id, preparation_time, calories, is_available, is_featured, is_popular, is_vegetarian, is_spicy, created_at, options) values ('mi-9', 'سمك فيليه مشوي', 'Grilled Fish Fillet', 'فيليه سمك مشوي مع أعشاب وبهارات خاصة', 'Grilled fish fillet with herbs and special spices', 130, '/images/categories/seafood.jpg', 'cat-4', 22, 280, true, false, false, false, false, '2024-01-06', NULL) on conflict (id) do nothing;
insert into menu_items (id, name_ar, name_en, description_ar, description_en, price, image, category_id, preparation_time, calories, is_available, is_featured, is_popular, is_vegetarian, is_spicy, created_at, options) values ('mi-10', 'فتوش', 'Fattoush', 'سلطة خضراء مقرمشة مع خبز محمص وسماق', 'Crispy green salad with toasted bread and sumac', 35, '/images/menu/fattoush.jpg', 'cat-5', 8, 150, true, false, true, true, false, '2024-01-01', NULL) on conflict (id) do nothing;
insert into menu_items (id, name_ar, name_en, description_ar, description_en, price, image, category_id, preparation_time, calories, is_available, is_featured, is_popular, is_vegetarian, is_spicy, created_at, options) values ('mi-11', 'حمص', 'Hummus', 'حمص ناعم مع طحينة وزيت زيتون وبابريكا', 'Creamy hummus with tahini, olive oil, and paprika', 30, '/images/menu/hummus.jpg', 'cat-5', 5, 220, true, false, true, true, false, '2024-01-01', NULL) on conflict (id) do nothing;
insert into menu_items (id, name_ar, name_en, description_ar, description_en, price, image, category_id, preparation_time, calories, is_available, is_featured, is_popular, is_vegetarian, is_spicy, created_at, options) values ('mi-12', 'بابا غنوج', 'Baba Ganoush', 'باذنجان مشوي مهروس مع طحينة وثوم وليمون', 'Smoky roasted eggplant dip with tahini, garlic, and lemon', 30, '/images/menu/baba-ganoush.jpg', 'cat-5', 5, 180, true, false, false, true, false, '2024-01-02', NULL) on conflict (id) do nothing;
insert into menu_items (id, name_ar, name_en, description_ar, description_en, price, image, category_id, preparation_time, calories, is_available, is_featured, is_popular, is_vegetarian, is_spicy, created_at, options) values ('mi-13', 'جناحات دجاج', 'Chicken Wings', 'جناحات دجاج مشوية متبلة مع صوص البافلو', 'Spicy grilled chicken wings with buffalo sauce', 75, '/images/menu/wings.jpg', 'cat-5', 15, 450, true, false, false, false, true, '2024-01-07', NULL) on conflict (id) do nothing;
insert into menu_items (id, name_ar, name_en, description_ar, description_en, price, image, category_id, preparation_time, calories, is_available, is_featured, is_popular, is_vegetarian, is_spicy, created_at, options) values ('mi-14', 'أرز باللبن', 'Rice Pudding', 'أرز باللبن مع قرفة ومكسرات', 'Creamy rice pudding with cinnamon and nuts', 25, '/images/menu/rice-pudding.jpg', 'cat-5', 5, 280, true, false, false, true, false, '2024-01-08', NULL) on conflict (id) do nothing;
insert into menu_items (id, name_ar, name_en, description_ar, description_en, price, image, category_id, preparation_time, calories, is_available, is_featured, is_popular, is_vegetarian, is_spicy, created_at, options) values ('mi-15', 'عصير مانجو', 'Mango Juice', 'عصير مانجو طازج وطبيعي', 'Fresh natural mango juice', 35, '/images/categories/drinks.jpg', 'cat-6', 3, 180, true, false, true, true, false, '2024-01-01', NULL) on conflict (id) do nothing;
insert into menu_items (id, name_ar, name_en, description_ar, description_en, price, image, category_id, preparation_time, calories, is_available, is_featured, is_popular, is_vegetarian, is_spicy, created_at, options) values ('mi-16', 'عصير فراولة', 'Strawberry Juice', 'عصير فراولة طازج وطبيعي', 'Fresh natural strawberry juice', 35, '/images/categories/drinks.jpg', 'cat-6', 3, 160, true, false, false, true, false, '2024-01-02', NULL) on conflict (id) do nothing;
insert into menu_items (id, name_ar, name_en, description_ar, description_en, price, image, category_id, preparation_time, calories, is_available, is_featured, is_popular, is_vegetarian, is_spicy, created_at, options) values ('mi-17', 'عصير ليمون ونعناع', 'Lemon Mint Juice', 'عصير ليمون طازج مع نعناع', 'Fresh lemon juice with mint', 25, '/images/categories/drinks.jpg', 'cat-6', 3, 80, true, false, false, true, false, '2024-01-03', NULL) on conflict (id) do nothing;
insert into menu_items (id, name_ar, name_en, description_ar, description_en, price, image, category_id, preparation_time, calories, is_available, is_featured, is_popular, is_vegetarian, is_spicy, created_at, options) values ('mi-18', 'مياه معدنية', 'Mineral Water', 'مياه معدنية', 'Mineral water', 10, '/images/categories/drinks.jpg', 'cat-6', 1, 0, true, false, false, true, false, '2024-01-04', NULL) on conflict (id) do nothing;
